INSERT INTO asset (name, price) VALUES ('Reliance Industries', 2350.75);
INSERT INTO asset (name, price) VALUES ('Tata Consultancy Services', 3250.50);
INSERT INTO asset (name, price) VALUES ('HDFC Bank', 1505.25);
INSERT INTO asset (name, price) VALUES ('Infosys', 1450.00);
INSERT INTO asset (name, price) VALUES ('Hindustan Unilever', 2600.10);
INSERT INTO asset (name, price) VALUES ('ICICI Bank', 720.30);
INSERT INTO asset (name, price) VALUES ('Kotak Mahindra Bank', 1840.75);
INSERT INTO asset (name, price) VALUES ('Larsen & Toubro', 1960.85);
INSERT INTO asset (name, price) VALUES ('State Bank of India', 550.65);
INSERT INTO asset (name, price) VALUES ('Bajaj Finance', 6450.90);
INSERT INTO asset (name, price) VALUES ('Bharti Airtel', 790.45);
INSERT INTO asset (name, price) VALUES ('Asian Paints', 2990.30);
INSERT INTO asset (name, price) VALUES ('HCL Technologies', 1130.50);
INSERT INTO asset (name, price) VALUES ('Maruti Suzuki', 8750.25);
INSERT INTO asset (name, price) VALUES ('Sun Pharma', 960.35);
